name: Swift

on: 
  push:
    branches:
      - main
  pull_request:
    branches: 
      - main

jobs:
  build:

    runs-on: macOS-latest
    
    steps:
    - uses: actions/checkout@main
    - name: Start xcodebuild test
      run: xcodebuild clean test -project InterviewPractices.xcodeproj -scheme InterviewPractices -destination "platform=iOS Simulator,name=iPhone 12 Pro"
